image: ubuntu:latest

before_script:
  - "apt-get update"
  - "apt install maven -y"

stages:
  - build_test_package_ships
  - build_test_package_ring

build_test_package_ships:
  stage: build_test_package_ships
  tags:
    - docker-hse
  script:
    - cd Ships
    - mvn clean compile
    - mvn clean test
    - mvn clean package
  artifacts:
    paths:
      - /builds/hseoop2019/krupinmi-hw3/Ships/target/Ships.jar

build_test_package_ring:
  stage: build_test_package_ring
  tags:
    - docker-hse
  script:
    - cd TokenRing
    - mvn clean compile
    - mvn clean test
    - mvn clean package
  artifacts:
    paths:
      - /builds/hseoop2019/krupinmi-hw3/TokenRing/target/TokenRing.jar
